name       : kwin
version    : 5.16.1
release    : 42
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kwin-5.16.1.tar.xz : e5cb08a116e1a60a60fb1f375e72cb4f8d01c8f31b3456b48bc5c72b5907260f
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libcap)
    - pkgconfig(libinput)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(wayland-cursor)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kidletime-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kscreenlocker-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
    - qt5-virtualkeyboard
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-snappier-animations.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
