name       : kwin
version    : 5.18.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.3/kwin-5.18.3.tar.xz : e2dceee95fdb74ab1cfca4912731c20c9ff363d20b8f1872185eefa4a4ee69a4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libcap)
    - pkgconfig(libinput)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5VirtualKeyboard)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(wayland-cursor)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kidletime-devel
    - kinit-devel
    - kio-devel
    - kirigami2-devel
    - knewstuff-devel
    - knotifications-devel
    - kscreenlocker-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
    - qt5-virtualkeyboard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
