name       : kwin
version    : 5.15.3.2
release    : 35
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/kwin-5.15.3.2.tar.xz : 3c7b5ced440cf9ecd23b5905727cea4730188fbfe6388b4fcdb5eb3f52323147
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libcap)
    - pkgconfig(libinput)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(wayland-cursor)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kidletime-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kscreenlocker-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
rundeps    :
    - qt5-virtualkeyboard
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-snappier-animations.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
