name       : kwin
version    : 5.13.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/kwin-5.13.3.tar.xz : 7f069710a2c85c362dc5d1bbe25f54b46fa6ff4cf287c8d1a46bd43cf3f3cbaa
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libcap)
    - pkgconfig(libinput)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidletime-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kscreenlocker-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-virtualkeyboard
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Use-snappier-animations.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
