name       : kwin
version    : 5.27.7
release    : 110
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/kwin-5.27.7.tar.xz : cbff55ba018463bc05ba286663aea1d7b0f48993dc3c778b5514e34fcdb95a2f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-only
component  : desktop.kde.core
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
optimize   : lto
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gbm)
    - pkgconfig(lcms2)
    - pkgconfig(libcap)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libxcvt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5VirtualKeyboard)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(wayland-cursor)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - kactivities-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kidletime-devel
    - kinit-devel
    - kio-devel
    - kirigami2-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwayland-devel
    - wayland-protocols-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - kirigami2
    - qt5-virtualkeyboard
    - plasma-framework
patterns   :
    - /usr/lib64/libkdeinit5*.so
replaces   :
    - kwayland-server
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
